name: "My action"
description: "Test my action"

inputs:
  message:
   description: "The message to print"
   required: true
   default: "Hi from my custom action!"

runs:
  using: "composite"

  steps:
    - name: "Hello world!"
      run: echo "${{ inputs.message }}"
      shell: bash
