# First step define a name
name: Hello world!

# Next step is define an event that execute this workflow
on: 
  push:
    branches:
      - main
  pull_request: 
    branches: 
      - main

# Now you need a job to define the step by step that you need on this workflow
jobs:
  first-job: 
    runs-on: ubuntu-latest

    steps:
        - name: Hello world
          run: echo "Hello world"

        - name: Touch file
          run: touch hello.txt

        - name: Set text
          run: echo "Hello world" >> hello.txt

        - name: Read file
          run: cat hello.txt

  second-job: 
    runs-on: ubuntu-latest
    needs: [first-job]
    steps:          
      - name: Checkout     
        uses: actions/checkout@v4.1.7
      - name: LS
        run: ls -al
