name: Enviroment variables

on: [push]

jobs:
  variables:
    runs-on: ubuntu-latest

    env: 
        MY_VAR: My enviroment variable

    steps:
      - name: Test
        env:
            STEP_MY_VAR: Step Scope
        run: "echo Valor: $STEP_MY_VAR"